version: '3'
services:
  app:
    image: repoflow/microservice-certificates-container:linked
    env_file:
      - .env
    ports:
     - "4000:4000"
    volumes:
      - /home/victor/cluster/certificates/vicjicama.com:/certbot
